### PR TITLE
Unit 6.1

### PR DESCRIPTION
**Pull request by collincahill**
Along with a review of the PR, looking for a second opinion: Is there any way I can still use `gulp-connect` and `gulp-sass` or should I get rid of them?

### CODE REVIEW

**Comment by kddrake** [comment]
I know this would royally suck... but maybe it would be worth it to see if there isn't a better solution than Mongodb for a backend? Honestly the only reason we're using it is because it's what I used when I was an intern. Might be just as beneficial to replace it just as we are with Angular v1.

[Firebase](https://firebase.google.com/) might be something to look into. I'm _pretty sure_ (but don't have much reason to be) it'd be pretty easy to integrate into the project. And it's free. I've used Firebase a tiny bit and I remember it being quite easy to configure and set up. From what I've heard, Polymer and Firebase play very well together.

**Comment by rginther** [comment]
Firebase IS the goto for Polymer. Honestly. I would second changing the intern onboarding project instructions to use Firebase rather than MongoDB. @kddrake

**Comment by collincahill** [comment]
I came across Firebase while I was researching but thought MongoDB might be what I end up working with a bit more. I ultimately didn't use Firebase because it's entirely hosted by Google.
Firebase has web components for queries already! So that is nice.
The only other alternative that seemed promising in my research was [CouchDB](http://couchdb.apache.org/), which I know very little about.

**Comment by rginther** [comment]
We could just leave it open to whoever is working on the onboarding project. I don't think there is really many benefits using this one or that one. Just whatever people prefer.

**Comment by kddrake** [comment]
> ... thought MongoDB might be what I end up working with a bit more.

@collincahill this is actually, in my experience, the only time you'll be using Mongodb (for something work related)

> We could just leave it open to whoever is working on the onboarding project.

Thought about this as well. As long as we have a couple options that aren't complicated to implement or understand, I'd be OK with that. Something to discuss when I/we actually overhaul the onboarding project.

**Comment by collincahill** [comment]
@kddrake What kind of database do you work with normally?

**Review by rginther — APPROVED** [review]
This looks good to me! Going to go ahead and merge. 👍

**Comment by kddrake** [comment]
@collincahill Honestly, I have no idea what we use in the way of dbs. We don't really deal with them (at my level on the UX team).

**Pull request merged**
